version: "3.7"

volumes:
  postgres:
  pgadmin:

networks:
  network:
    driver: bridge

services:
  pgadmin:
    image: dpage/pgadmin4:7.7
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    healthcheck:
      test: wget -qO- http://127.0.0.1:80 | egrep csrf_token
      interval: 30s
      timeout: 3s
      retries: 5
    depends_on:
      - postgres
    networks:
      - network

  postgres:
    image: postgres:16.0-alpine
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USERNAME}
      interval: 30s
      timeout: 3s
      retries: 5
    networks:
      - network
